version: "3"
services:
  app:
    # add the actual image here
    image: chebishev/jenkins-test:alpha
    ports:
      - "3030:3030" # Map port 3030 on the host to port 3030 in the container
    environment:
      - NODE_ENV=production
